#
# MediaWiki integration
#

:mediawiki:

  # URL of the MediaWiki API endpoint
  :endpoint: http://gslug.org/wiki/api.php

#
# Calendar
#

:calendar:

  # URL of iCalendar feed
  :feed_url: https://www.google.com/calendar/ical/dksq9gdtuasak0v97g59tnpo60%40group.calendar.google.com/public/basic.ics

  # Regular expression to be matched against calendar events to identify meetings
  :meeting_regex: !ruby/regexp /GSLUG/

#
# Templates
#

:templates:

  # Template for meeting pages
  :meeting: templates/meeting.wiki.erb

  # Directory of file templates to build automatically
  :local_files: templates/auto_local-files

  # Directory of wiki page templates to publish automatically
  :wiki_pages: templates/auto_wiki-pages

# Directory in which to build local files
:build_path: build
